# twitter api
export CONSUMER_KEY=YOUR_CONSUMER_KEY
export CONSUMER_SECRET=YOUR_CONSUMER_SECRET
export ACCESS_KEY=YOUR_ACCESS_KEY
export ACCESS_SECRET=YOUR_ACCESS_SECRET

# treasure data api
export TD_API_KEY=YOUR_TD_API_KEY
